### ISSUE TITLE
Create AppStudio Samples

### ISSUE THREAD

**Issue by nohe427** [Esri/developer-support#109]
@bsnider has been tasked with creating AppStudio Samples.

The samples are designed to showcase a particular component (or small number of related components) without the clutter of a full app. Users should be able to copy qml from a sample (preferable taking a whole qml file) and drop it into their own app. 

These are the samples he needs:
- [x] Edit points, lines and polygons –Edit existing features and allow the user to delete and move vertices of existing features, and delete whole features.
- [x] Attribute editing – Select an existing feature and edit its attributes.
- [x] Related record editing – (may be a part of the previous sample or separate) Select an existing feature and edit the attributes of related records.
- [x] Capture lines and polygons - Capture a new line or polygon feature with either screen taps or GPS/Location coordinates
- [x] Snapping line features - (may be a part of the previous sample or separate) Capture a new line or polygon feature by tapping on existing feature vertices.

We also need to strive to emphasis offline capabilities, but also want to avoid filling every sample with download geodatabase code. Consider variations amongst the samples listed above, for example in some you may pre-supply a geodatabase, others may download and some can edit online. Perhaps if number 4 in the list is offline, 5 can be online (as it shows similar functionality).

@bsnider and I will be discussing this in our group meetings.

Please mention which one you would like to work on when you begin working on it.

Looking for help from @goldenlimit @marlak @gdhakal @guo7711 @andr7430 @natas333x2

**Comment by nohe427** [comment]
I call dibs on:

Capture lines and polygons - Capture a new line or polygon feature with either screen taps or GPS/Location coordinates

**Comment by marlak** [comment]
Sounds like a good challenge...I'm in! 

I'll take this slice of the :cake: 
Attribute editing – Select an existing feature and edit its attributes

**Comment by bsnider** [comment]
Thanks @nohe427 and @marlak!  Let's make some cool :telephone: apps!

**Comment by bsnider** [comment]
Kevin Burke has taken on the Edit points, lines and polygons sample!  He will be joining us on GitHub soon

**Comment by andr7430** [comment]
I will take number :three:

**Comment by bsnider** [comment]
Thanks @andr7430!

**Comment by nohe427** [comment]
As discussed in last nights meeting I believe @goldenlimit is taking on issue number 5?

**Comment by goldenlimit** [comment]
My sample for Snapping Line feature is coming :ocean:

**Comment by nohe427** [comment]
Are all of these samples uploaded?  Can we close this issue?

@bsnider @marlak @andr7430 @goldenlimit

**Comment by goldenlimit** [comment]
@nohe427 I have a new version that haven't update here but I already updated to AppStudio team. I will do it today!

**Comment by nohe427** [comment]
@goldenlimit Awesome!  I appreciate it!

**Comment by nohe427** [comment]
I believe all samples have been merged into the appstudio official samples.
