### ISSUE TITLE
ES2015 Samples

### ISSUE THREAD

**Issue by benstoltz** [Esri/developer-support#122]
So as some of you may be aware there is a new version of ECMAScript out known as ES2015. It introduces new syntax and some different ways of developing with our JS api. I've been working on a few samples. I propose creating a new folder to hold these samples.

Thoughts?

**Comment by NoashX** [comment]
Sounds like a good idea to me @benstoltz!

**Comment by nohe427** [comment]
Let's see these samples @benstoltz :space_invader: :octocat:

**Comment by benstoltz** [comment]
Just getting everything polished up with documentation. Soon...soon.

**Comment by jgravois** [comment]
we're always happy to accept new samples, but this doesn't require an issue to be held open.

**Comment by benstoltz** [comment]
@jgravois yeah, this was originally more of a reminder for me. Life got away so haven't worked on it. I'll get some pr's going at some point.
