### ISSUE TITLE
web-leaflet MultMaps sample has map missing

### ISSUE THREAD

**Issue by NoashX** [Esri/developer-support#129]
looks like the sample here: http://esri.github.io/developer-support/web-leaflet/multiple-maps-connected-extent/index.html

has some missing tiles in the first map (e.g. https://b.tiles.mapbox.com/v3/examples.map-i875mjb7/8/68/95.png)

![mapdown](https://cloud.githubusercontent.com/assets/2190813/10236293/ced65ada-6858-11e5-90f6-11332aa984a7.png)

**Comment by benstoltz** [comment]
Yeah, it seems like the original mapbox map ID is no longer valid. We just need to update it to one that works.

**Comment by goldenlimit** [comment]
This issue has been fixed. https://github.com/Esri/developer-support/issues/133
Therefore we closed :smiley:
