### ISSUE TITLE
condemn force pushing 

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#143]
we should mention explicity in the readme that pushing your own commits directly to `master` is strongly discouraged and that force pushing is strictly **prohibited**, ideally going as far as mimicing the exact rules [Level](https://github.com/Level/community/blob/master/CONTRIBUTING.md) lists for their OPEN open source projects.

~~i'd even recommend we go [a step further](
https://help.github.com/enterprise/11.10.340/admin/articles/blocking-force-pushes-to-a-repository/)~~

**Comment by benstoltz** [comment]
I'm 100% on board with that, including your step further.

**Comment by NoashX** [comment]
Agreed on the first. I think we can better message this internally. 

The further step concerns me in case there are ever legitimate reasons to self-publish (e.g. fix README typos).  Thoughts?

**Comment by jgravois** [comment]
force pushing is substantially different than a simple push to fix a typo in a file no one else has edited.  it is typically only attempted when a normal push fails (either because of a merge conflict or difference in the commit history between the clone and the upstream repository
```bash
git push upstream master
>  ERR
git push upstream master -f
> will succeed and blow away whatever history was present (overwriting with your own)
```
there is **never** a good reason for anyone to force push to the `master` branch of this repository **ever** and depending on the situation it could be an absolute nightmare to recover from.

the dreaded 'step further' i mentioned is probably not worth discussing, because it appears its [only an option](http://stackoverflow.com/questions/5094524/github-prevent-collaborators-from-using-push-f) for an enterprise instance of github.

**Comment by nohe427** [comment]
I'd say just get a few managers with merge access.  Other people can still test code and put their thoughts into the issue and when it is ready to be merged in, tag the manager with their @ username call.  e.g. @jgravois

**Comment by jgravois** [comment]
> I'd say just get a few managers with merge access

i understand the appeal, but my vote is that we keep it more of an [open, open source](https://github.com/moose-team/friends/blob/master/CONTRIBUTING.md#collaborating-guidelines) project.  

i think we have enough to gain from an educational perspective to justify the risk.

**Comment by benstoltz** [comment]
I would agree with @jgravois. However I'd say that if someone abused the open nature of this project that they may have their write access revoked. Obviously one or two mistakes wouldn't justify that response, however if it's repeated and consistent then I think that's an appropriate response. Thoughts?

**Comment by jgravois** [comment]
i went that [step further](https://github.com/blog/2051-protected-branches-and-required-status-checks).  because they are 'protected branches', it is no longer possible to force push to either `master` or `gh-pages`

**Comment by phpmaps** [comment]
gone are the days of force pushing.  I will sleep better.

**Comment by NoashX** [comment]
:+1:
