### ISSUE TITLE
add a simple 'how to' or 'instructions for beginners' to the main readme

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#144]
looking over the homepage it strikes me that our doc for contributors is a lot more fleshed out than the 95% of users who just want to download and check out the samples...

**Comment by NoashX** [comment]
I worked with @bsnider on a blog about this, targeted towards "Download ZIP" rather than "Clone in Desktop" type users (if that analogy makes sense). It's currently being reviewed.

**Comment by jgravois** [comment]
to clarify what i mean, i'm suggesting a new section in the projects main README which provides some simple instructions for making use of the project aimed at those who are not *contributors*, but rather *consumers*.

if someone looking to get more experience with Git/GitHub wants to help with this, that would be ideal.
