### ISSUE TITLE
Please add guidelines for contributing samples in the main README.md

### ISSUE THREAD

**Issue by alaframboise** [Esri/developer-support#155]
It would be helpful if we published the basic format that was expect for the samples that people want to contribute. Or better yet, even a template.

e.g. 

TechnologyCategory/Folder/xxx
TechnologyCategory/Folder/README.md

README.md could contain things like...
- How to get it working
- Requirements
- See it live here...

Few other ideas: A high-level README.md in each TechnologyCategory folder would be helpful to see a list of what's there.

Thanks,
AL

**Comment by jgravois** [comment]
:+1:

**Comment by NoashX** [comment]
I concur. Are you imagining something more comprehensive than the current CONTRIBUTING.md
https://github.com/Esri/developer-support/blob/master/CONTRIBUTING.md

Or just placing that content (with a few updates) inside the README.md?

**Comment by alaframboise** [comment]
Actually, a few things:

1. There's Esri's contributing.md guidelines which is something different than the format we would like to see for samples. Please separate those from the contribution guidelines for samples.
2. Put a clear 1-2-3 example right in the main README.md that shows people exactly what we are looking for in a sample. e.g. folder\xxx folder\readme.md, folder\other...
3. And then there's what goes in the README.md for each. Example of that.
4. Another suggestion was to have a single location, possible README.md in each high-level category that gives an outline of what's in there, otherwise you are have to click into each one to explore. You could also use wiki for this. The best way would be to have an build that picks up this content from every README.md and maybe builds out a simple index.html in gh-pages.

The overall goal is to make it easier for people to find stuff and contribute.

**Comment by phpmaps** [comment]
Well the good news is most contributors have added README's with there samples and the format is fairly consistent.  The bad news is there are around 100 samples in the repo which I am assuming need this new style documentation right?

**Comment by jgravois** [comment]
its a good idea, but no one has taken the bait.
