### ISSUE TITLE
Web AppBuilder (Developer Edition) pointing to ArcGIS for Server

### ISSUE THREAD

**Issue by ezequias** [Esri/developer-support#185]
Hi everyone

I would like if it is possible to point WAB to an ArcGIS for Server service.

If yes please could you tell me further steps?

Best regards
Ezequias Rocha

**Comment by NoashX** [comment]
Hi Exequias, I see that you had a similar question here on GeoNet: https://geonet.esri.com/thread/170986

WAB (dev ed) requires ArcGIS Online or Portal for ArcGIS to install. After this, it is possible to use something like the Local Layer Widget that Robert suggested.

Can you explain a bit more about your workflow, and where you are having trouble?

**Comment by ezequias** [comment]
I am working on a project and I have a ArcGIS for Server 10.3 license and would like to use it's services in a simple web application with javascript.

My web application would have with some basic feature like navigation/geocoding/search-by-attribute/print/enabeling layers and legend.

The steps LocalLayer Widget suggest me where to complicated for me.

Sincrely
Ezequias Rocha

**Comment by NoashX** [comment]
Ok, here's a couple of options. First, please note that the instructions for installing the Web AppBuilder must be followed to get up and running, and that WAB does not support consuming Map Services directly (they need to be stored in a webmap in AGOL or Portal).

1) WAB dev ed
https://developers.arcgis.com/web-appbuilder/guide/getstarted.htm
Follow these instructions, add the map services from ArcGIS Server to AGOL as a webmap, and add the widget you desire. If Local Layer Widget is too complicated, here is an alternative approach:
https://github.com/Esri/developer-support/tree/master/web-app-builder/add-feature-layer

2) WAB AGOL version
Same as above, but less complicated as there is no installation
http://doc.arcgis.com/en/web-appbuilder/

3) JavaScript API
https://developers.arcgis.com/javascript/jshelp/intro_firstmap_amd.html
If you are a programmer, you can either build the app from scratch, or mashup a few samples together to achieve the functionality you are looking for.
https://developers.arcgis.com/javascript/jssamples/

If you need more help, GeoNet might actually be a better place to discuss workflows. Or, please contract Technical Support if you have that option available. This space is more for logging problems and enhancements for code.

Hope this helps!
