### ISSUE TITLE
no need to use the word 'repository' in the project readme title

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#195]
> #### Developer Support ~~Repository~~
> Welcome to the Developer Support ~~Respository~~ (Re*s*pository???)

all github projects are repositories :smile:

**Comment by nohe427** [comment]
I think a lot of people use the word repository in their readme files.  If you look at Microsofts for vscode, they have the word repository used to describe what the location is:  
https://github.com/Microsoft/vscode

Another example:
https://github.com/Microsoft/dotnet-apiport

While it is inherently obvious what it is, this type of language is common in English.  For example (might be a bad example), if I wanted you to look at a map of Las Vegas, I would not tell you to look at Las Vegas.  I would tell you to look at the Las Vegas map.

While I do think the wording could be changed for our repo, I also do not think it necessary to change.  In addition, I do not think that an attempt to remove all of the "repository" words would be of benefit.  Maybe:

### Esri's Developer Support
##### Welcome to Esri's Developer Support

But then, we might need to be a little more clear that this is a samples only section of Esri, not the support operations center.

**Comment by MarieAshley** [comment]
I think it's fine the way it is. It's not quite as bad as "The department of redundancy department." :smiley:  However, if we want to keep at short and sweet, "Welcome to Developer Support" or "Welcome to Esri's Developer Support" seems perfectly acceptable as well.

**Comment by jgravois** [comment]
> I think a lot of people use the word repository in their readme files

thats true, but neither one of your examples use the word in the title.  i edited the title to clarify.

i'm not suggesting we eradicate every last mention of the word *repository*, i'm just providing some persnickety copyediting suggestions.  i count 5 references (one misspelled) between the title(s) and introduction to the project and it feels like too much.

> But then, we might need to be a little more clear that this is a samples only section of Esri

additional clarity could certainly be provided.

to be honest, i'm not really that concerned about it.  i just noticed wording that could be improved and felt like it'd be more valuable to leave a breadcrumb for someone new to take a stab at submitting their first Pull Request than it would be to suggest the exact fix myself.

i'm happy to just leave it be if no one else is bothered or interested in making the suggested copyedits.  i won't lose any sleep over it. :smile_cat:

**Comment by nohe427** [comment]
I get what you are saying.  Sounds good :+1:
