### ISSUE TITLE
Value error while pinging

### ISSUE THREAD

**Issue by trillevine** [Esri/developer-support#202]
Hello,

I'm testing out this script and am getting a value error stemming from this line:

![ping](https://cloud.githubusercontent.com/assets/7161139/13072186/1664ee6a-d498-11e5-94e1-b01560158ac4.PNG)

The traceback reads:

![ptrace](https://cloud.githubusercontent.com/assets/7161139/13072203/3357de88-d498-11e5-8714-55d4e5e84c2b.PNG)

Any ideas?  I'm using Python 2.7...I might be wrong, but the problematic line looks like 3.X formatting, correct?  If so, how could this line be modified for 2.7?  Any feedback is greatly appreciated!

**Comment by ceddc** [comment]
Hi,

Related to : https://github.com/Esri/developer-support/blob/4be899d846c691998a919b6d2093b8bcd8ced583/python/general-python/create-replica-and-download/createReplicaAndDownload.py

Are you sure you are using python 2.7 and not 2.6 (check system variable, or run <fullpath to 2.7>/python)

Cf : http://stackoverflow.com/questions/5446964/valueerror-zero-length-field-name-in-format-error-in-python-3-0-3-1-3-2

> Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'.

**Comment by trillevine** [comment]
Hi, thanks for the response, sorry for the delay, was out sick last week.  You're right, I'm using 2.6 on this machine, my mistake...have 2.7 on another virtual machine.  Will check these links out, thanks for the info!
