### ISSUE TITLE
Empty Zip File

### ISSUE THREAD

**Issue by trillevine** [Esri/developer-support#207]
Hello,

I've been using this script daily for two weeks without problems, but since yesterday I keep getting an empty zip folder as my result.  I've tried it with several different services and it's happening regardless.  Any ideas?  Feedback greatly appreciated!!!

**Comment by ceddc** [comment]
Hi,

please link to the script you are using ! :smile:

**Comment by trillevine** [comment]
Hi, sorry -- this one:

https://github.com/Esri/developer-support/edit/master/python/general-python/create-replica-and-download/createReplicaAndDownload.py

**Comment by MarieAshley** [comment]
Hey!

After the script completes, type jsonResponse into the interpreter. You should see a resultUrl. Grab that url and paste it into a browser. Does the replica download? This may help isolate the issue.

**Comment by trillevine** [comment]
Hi, when I toss the jsonResponse URL into Firefox, I get the following response:

![jsonresponse](https://cloud.githubusercontent.com/assets/7161139/13461775/e6fa4aec-e083-11e5-84c8-5e1b879679d3.PNG)

FWIW, I'm also on the ArcRest repository mailing list, and someone just opened an issue with the same problem.  Maybe it's something on the server side.

**Comment by MarieAshley** [comment]
Resolved in https://github.com/Esri/developer-support/pull/208
:smiley:
