### ISSUE TITLE
duplicate 'live sample links' in 4.x extrude sample

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#218]
https://github.com/Esri/developer-support/tree/master/web-js/4.x/extrude

there should be only one

**Comment by jgravois** [comment]
looking for help from someone new-ish to github

**Comment by NoashX** [comment]
i think they are two different links with the same name? the repo has two different sample apps in it...

**Comment by jgravois** [comment]
> the repo has two different sample apps in it.

good point.  i think it'd be clearer though if the text of the links provided some differentiation.

**Comment by jgravois** [comment]
to clarify, i meant that we update the readme to something like this:

[Live Sample - NYC](http://esri.github.io/developer-support/web-js/4.x/extrude/nyc.html)
[Live Sample - Cube](http://esri.github.io/developer-support/web-js/4.x/extrude/cube.html)

**Comment by jgravois** [comment]
closed via 7d82b67
