### ISSUE TITLE
time to prune stale branches

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#219]
we have quite a few stale branches in this repository that can/should be deleted.

https://github.com/Esri/developer-support/branches

most have already been merged.  the only one ahead of master is 'Nick's-Branch', but i've confirmed with @nhaney90 that the commits made their way into `master` so it can be deleted as well.

**Comment by benstoltz** [comment]
@jgravois Cleaned up most of them. Should be good to go.
