### ISSUE TITLE
remove cedar-charts-guage sample

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#220]
https://github.com/Esri/developer-support/tree/master/web-js/cedar-charts-guage

this is why we do code review... assigning to sample author.

**Comment by phpmaps** [comment]
I can add it.

**Comment by jgravois** [comment]
thanks.  **please** create a branch and PR.

**Comment by jgravois** [comment]
@phpmaps please create a README to document your sample.

**Comment by jgravois** [comment]
your web-leaflet/[drag-drop-geocoding](https://github.com/Esri/developer-support/tree/gh-pages/web-leaflet/drag-drop-geocoding) sample needs a README too. particularly since the sample doesn't work because you hardcoded a stale token.

for the last time, **PLEASE** start participating in code review.  the samples you are pushing up on your own are desperately in need of it.

**Comment by phpmaps** [comment]
@marlak @jgravois  Humm.. Marla did the code review.  I also think you checked in the gh-pages work which intentionally did not have a readme.  I merged nada.

**Comment by jgravois** [comment]
okay.  i see.  the confusion here is caused by the fact that you thought that the `gh-pages` branch of this repository was supposed to contain different content than the `master` branch. they are supposed to be identical.  

so i must have unintentionally removed the README you included in your PR against the `master` branch when i synchronized.  my apologies.

looking at the history is appears you never pushed up a readme for the `cedar-charts-guage` sample, but who knows, it could be floating around somewhere.

**Comment by jgravois** [comment]
still waiting on a cedar-charts-guage README from @phpmaps or any other kind soul.  to get even more nitpicky, ***gauge*** is misspelled.

**Comment by phpmaps** [comment]
John please delete this content.  It’s proving to be more of a hassle then value.

**Comment by jgravois** [comment]
i'm *95%* sure dougie is saying we should just remove the [`cedar-charts-guage`](https://github.com/Esri/developer-support/tree/gh-pages/web-js/cedar-charts-guage) sample entirely.

i've updated the issue name to reflect this.  still looking for volunteer to actually git-er done though.
