### ISSUE TITLE
'wgs-to-webmercator' sample readme needs a 'live sample' link

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#221]
https://github.com/Esri/developer-support/tree/master/web-js/wgs-to-webmercator

**Comment by jgravois** [comment]
you can find an example of what i'm asking for here:
https://github.com/Esri/developer-support/tree/master/web-js/buffer-geocoder-result#live-sample

is anyone willing to pitch in and contribute this update?

**Comment by nohe427** [comment]
I think since we deleted the master branch, the sample can be found here now:

https://github.com/Esri/developer-support/tree/gh-pages/web-js/wgs-to-webmercator

Therefore the gh-page can be found here:

http://esri.github.io/developer-support/web-js/wgs-to-webmercator/
