### ISSUE TITLE
Static map class using JavaScript API

### ISSUE THREAD

**Issue by hhkaos** [Esri/developer-support#222]
A few months ago I create a class to make easier to generate static images, could I add a code sample using [this class](https://github.com/esri-es/Static-Maps-API-ArcGIS)?

Cheers,
Raul

**Comment by phpmaps** [comment]
Yes, please do collaboration is great.  Thanks Raul.

**Comment by goldenlimit** [comment]
@hhkaos Feel free to send a pull request to "web-js" folder, and make sure follow this contributing post: https://github.com/Esri/developer-support/blob/master/CONTRIBUTING.md

Thanks for your efforts! Welcome

**Comment by hhkaos** [comment]
I hope this works! :) 
https://github.com/Esri/developer-support/pull/224

Thanks

**Comment by benstoltz** [comment]
Closing out this issue as a PR got merged back in April. Thanks @hhkaos!
