### ISSUE TITLE
Web AppBuilder Custom Widget Directory

### ISSUE THREAD

**Issue by hhkaos** [Esri/developer-support#225]
I publish a repo a few months ago with a list of custom widgets:
http://esri-es.github.io/Web-AppBuilder-Custom-Widgets/

Do you think that this could be something interesting to add [here](https://github.com/Esri/developer-support/tree/master/web-app-builder/)? I'm not sure because the source code is not hosted directly on that repo, instead it is linked to the owners original source.

Cheers,
Raul

**Comment by NoashX** [comment]
Hi @hhkaos, I do not think that this is the best place for a list of custom widgets. We really want to focus on code that we and the community have written ourselves. Thank you for thinking of us, and perhaps you could promote this resource on `[GeoNet](https://geonet.esri.com/welcome)`?

**Comment by jgravois** [comment]
i think having a link to your external app in a generic `./web-app-builder/README.md` would be helpful for folks that are trolling for sample code.

**Comment by NoashX** [comment]
:+1:

**Comment by hhkaos** [comment]
Great John, that would be great :)

**Comment by jgravois** [comment]
lets leave this issue open until someone creates a Pull Request adding what i mentioned above.  this is another great opportunity for someone just getting started, so don't be shy if you need more clarification.

**Comment by hhkaos** [comment]
@jgravois I'm glad to create that README, what else should be inside? I'm checking but I can't see any root folder with README.md. 

Should we add links to external sites with resources for developers?, like: 
* [WAB videos at video.esri.com](http://video.esri.com/search/web-appbuilder)
* [GeoNet groups](https://geonet.esri.com/places?query=appbuilder)
* [Developers site documentation](https://developers.arcgis.com/web-appbuilder/)
* [More WAB related projects on Esri's Github](https://github.com/esri?utf8=%E2%9C%93&query=appbuilder)
* [WAB presentations at proceedings](https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Aproceedings.esri.com%20appbuilder)
* etc. ?

**Comment by jgravois** [comment]
those all sound good to me.

**Comment by hhkaos** [comment]
Pull request done 😄
