### ISSUE TITLE
Cedar interacting with 3D Maps

### ISSUE THREAD

**Issue by Jimeno0** [Esri/developer-support#230]
Hi there,

Recently I was testing the 3D Maps and the Cedar Graphics and I have developed two little examples showing how Cedar works and how to make that the Cedar graphics interacts with the map. Those two examples are very similar:

* [First example using pie graphics](http://jimeno0.github.io/3DEsriMaps/3DmapCedarPie.html)

*  [Second example using horizontal bars graphics](http://jimeno0.github.io/3DEsriMaps//3DmapCedarBars.html)

I will be pleased to create a README.md explaining how it works and send a pull request to `./web-js` folder if you want. =)

**Comment by jgravois** [comment]
sorry for the delayed response.  that sounds great!
we're looking forward to reviewing your Pull Request.

**Comment by benstoltz** [comment]
I've somewhat adopted Cedar, so definitely interested in the samples :)
