### ISSUE TITLE
runtime-android/sync-gdb-in-background missing res folder

### ISSUE THREAD

**Issue by doneill** [Esri/developer-support#238]
I am trying to update the sync-gdb-in-background android demo, beyond adding the gradle wrapper and updating the ignore list there are references to resources but the **res** directory is missing.  I can try to piece together a res file based on what the project needs, but best if we can introduce a proper res folder.

**Comment by doneill** [comment]
I've resolved icons, styles, but the strings will be an issue :-)

**Comment by nohe427** [comment]
Hey @doneill,

Thanks for using my sample!  This is the string resources I am using:

```xml
<resources>
  <string name="app_name">BackgroundSyncGeodatabase</string>
  <string name="sync_notification_title">Portal View</string>
  <string name="sync_updating">GDB Sync in Progress</string>
  <string name="sync_done">GDB Sync Completed</string>
  <string name="sync_failed">GDB Sync Failed</string>
</resources>
```

I didn't include the res file so as to not bloat the repository with extra images and strings.  I was worried I was sending too much data.

Are there some other items I can assist with in regards to this sample?

**Comment by nohe427** [comment]
Hey @jgravois & @doneill !

The res file did not bloat the repository as much as I originally assumed it would.  I went ahead and included it in pull request #239

**Comment by doneill** [comment]
Thanks @nohe427, Yes you should include everything to allow a developer to build the module.  I updated the gitignore list which details the files that should not be included.  I also added the gradle wrapper jar file and scripts, I know this repo explicitly ignores jar files but we need it such that developers do not need to have Gradle on their machine to run the demo.  Google recommends this.

**Comment by nohe427** [comment]
Hey no worries. If we could chat about what should be required for Android
samples later, I would appreciate it

**Comment by doneill** [comment]
@nohe427 Merging that PR helped, but nothing is happening in the app.  I will dig deeper into the app source but on start I get the following app screenshot:  

![bg-sync](https://cloud.githubusercontent.com/assets/1308001/16281710/750029e4-387a-11e6-9441-2f45d6f402a1.png)

**Comment by nohe427** [comment]
Give it two minutes

**Comment by nohe427** [comment]
I have it set up with alarm manager in the intent service

**Comment by doneill** [comment]
@nohe427 So what is the user workflow?  Do you need to sync a database from another app?  Trying to verify this is working as expected.

**Comment by nohe427** [comment]
Hey @doneill ,
I think we resolved a lot of this offline.  Do you still have lingering questions here or can this be closed?

Thanks,
@nohe427

**Comment by doneill** [comment]
Thanks @nohe427, yes you can close as resolved.  Thanks!
