### ISSUE TITLE
What are your thoughts on splitting web-js into two folders: web-js-3x and web-js-4x?

### ISSUE THREAD

**Issue by bsnider** [Esri/developer-support#262]
Since these are two distinct APIs, I think it'd be clearer if we separated the two.

**Comment by NoashX** [comment]
hmm, there's already a 4.x folder inside web-js, is that not sufficient?

**Comment by bsnider** [comment]
That works for me, but should 3.x samples go in a 3.x folder for consistency?

**Comment by NoashX** [comment]
:boom: I like that idea. Allows for expansion into 2.x/5.x if necessary.

**Comment by jgravois** [comment]
consistency is nice, but trying hard not to create orphaned links on the internet is pretty nice too imo.

**Comment by NoashX** [comment]
@bsnider revisiting this issue, think we should leave the folders as-is for now, but moving forward, adopt the 4.x and 5.x folders for future releases... keeping 3.x samples in the main folder will prevent orphaned links as @jgravois mentioned... my vote is to close this out at this time

**Comment by jgravois** [comment]
inbox zero.
