### ISSUE TITLE
Two license files

### ISSUE THREAD

**Issue by nohe427** [Esri/developer-support#266]
Is there a reason that we have a LICENSE and a license.txt file in the root of this project?

I might just be confused on the licensing...

**Comment by jgravois** [comment]
there *should* be only one.

![highlander](http://media.tumblr.com/tumblr_m7bqzrLOAN1qb9t58.jpg)

**Comment by briantwatson** [comment]
@jgravois, you can close per #273

**Comment by jgravois** [comment]
@briantwatson do you not have permission?

**Comment by briantwatson** [comment]
@jgravois, fairly certain no.  Only option I have here is "new issue", although I have never personally closed one so I could be missing something.

**Comment by nohe427** [comment]
Screenshots?
@brianwatson

**Comment by nohe427** [comment]
Screenshots?
@briantwatson

**Comment by briantwatson** [comment]
@nohe427, <a href=http://i.imgur.com/vVBOF2Z.png>http://i.imgur.com/vVBOF2Z.png</a>

No close button at the bottom, nor an edit button up top

**Comment by jgravois** [comment]
1. follow the steps in https://github.com/Esri/contributing/issues/9 to get added to the Esri [organization](https://github.com/orgs/Esri/people?utf8=%E2%9C%93&query=briantwatson).
2. after that's done, let me know and i will add you to the [Developer Support](https://github.com/orgs/Esri/teams/developer-support) team
3. that will give you write access to this repo.

**Comment by nohe427** [comment]
@briantwatson  Do not create a new GitHub account.  You can use the existing one

**Comment by briantwatson** [comment]
@jgravois, I'm added to the Esri & ArcGIS orgs now.

**Comment by jgravois** [comment]
great. welcome to the [team](https://github.com/orgs/Esri/teams/developer-support).

**Comment by briantwatson** [comment]
Closed via #273, there can only be one!
