### ISSUE TITLE
how to use extra lib in typescript

### ISSUE THREAD

**Issue by dyh333** [Esri/developer-support#278]
there is a point clustering demo, https://developers.arcgis.com/javascript/3/jssamples/layers_point_clustering.html
and need an extra clusterlayer lib, which is loaded by 
var dojoConfig = { 
        paths: {
          extras: location.pathname.replace(/\/[^/]+$/, "") + "/extras"
        }
      };

but when i need to use it in angular2, how can i import this extra lib?

**Comment by jgravois** [comment]
any ideas @tomwayson @jwasilgeo ?

**Comment by tomwayson** [comment]
@dyh333 this can be closed since we answered it over in https://github.com/Esri/angular-esri-map/issues/311, right?

**Comment by jgravois** [comment]
indeed it can.  thx @tomwayson!

**Comment by dyh333** [comment]
yes, thanks @tomwayson . the issue has been several times ago. thanks again.
