### ISSUE TITLE
Error getting token

### ISSUE THREAD

**Issue by briankingery87** [Esri/developer-support#280]
I keep getting this error and all I've done is replace the username and password variables.

> Traceback (most recent call last):
  File "C:\Users\brian.kingery@vdot.virginia.gov\Desktop\Kingery\Python\itemSizeCSV\itemSizeCSV.py", line 34, in <module>
    t= ItemCounterHelper.agolAdmin(user,pw)
  File "C:\Users\brian.kingery@vdot.virginia.gov\Desktop\Kingery\Python\itemSizeCSV\ItemCounterHelper.py", line 22, in __init__
    self.__token, self.__ssl= self.__getToken(username, password)
  File "C:\Users\brian.kingery@vdot.virginia.gov\Desktop\Kingery\Python\itemSizeCSV\ItemCounterHelper.py", line 75, in __getToken
    return jres['token'],jres['ssl']
KeyError: 'token'

Any thoughts?

**Comment by nohe427** [comment]
Which script are you using?

**Comment by briankingery87** [comment]
I am an admin in my group and my username and password are correct. I am using this script...

https://github.com/Esri/developer-support/tree/gh-pages/python/general-python/export-feature-service-item-size-CSV

**Comment by nohe427** [comment]
Have you tried capturing the response through Fiddler to see exactly what is returned while running the script?

**Comment by nohe427** [comment]
@briankingery87 - Just tried this with my own username and password, it looks like usernames are case sensitive.  Can you login to ArcGIS Online and check the casing of your username?  This may resolve the issue.

**Comment by briankingery87** [comment]
It was the case sensitivity. It's currently running now so lets see what comes from it, fingers crossed!

**Comment by nohe427** [comment]
@briankingery87 - I look forward to hearing the results.

**Comment by briankingery87** [comment]
Worked like a charm. I am going to do the export users and a couple other ones later.

**Comment by nohe427** [comment]
@briankingery87  - Great!  Can we go ahead and close this issue as it seems we have resolved it?

**Comment by briankingery87** [comment]
Yes, thank you for the help
