### ISSUE TITLE
Folders for frameworks

### ISSUE THREAD

**Issue by hhkaos** [Esri/developer-support#281]
Hi guys?, what do you think about adding several folders for diferentes technologies as:
* web-angular (ionic, directives v1. v2...)
* web-node
* web-jquery (bootstrap, calcite, jquery mobile)
* web-knockout
* web-backbone
* web-ember
* web-react
* web-polymer
* web-calcite
* web-tools (webpack, rollup, systemjs, browserify, yeoman, grunt, babel..)

And then add a **readme.md** on each folder, even if we don't upload any samples. Something [like what I did with Web AppBuilder](https://github.com/Esri/developer-support/tree/gh-pages/web-app-builder)?.

I already collected this informations for the talk I made with Rene in the devsummit europe:

----

* Angular | Follow: [@tomwayson](https://github.com/tomwayson) & [@jwasilgeo](https://github.com/jwasilgeo) & [@dbouwman](https://github.com/dbouwman)
  * [2015 Video: Declarative Mapping Applications with AngularJS](http://www.esri.com/videos/watch?videoid=4321&channelid=LegacyVideo&isLegacy=true&title=declarative-mapping-applications-with-angularjs)
  * [Directives to help you use Esri maps and services in your Angular apps ](https://github.com/Esri/angular-esri-map)
  * [Esri-playground: Angular 2 & Esri 4](https://github.com/jwasilgeo/angular2-esri-playground)
  * [Ionic app demonstrating how to use the Esri ArcGIS API for JavaScript](https://github.com/jwasilgeo/ionic-esri-map)

* Leaflet | [@jgravois](https://github.com/jgravois) & [@patrickarlt](https://github.com/patrickarlt)
  * [2015 Video - Esri Leaflet: An introduction](http://www.esri.com/videos/watch?videoid=4314&channelid=LegacyVideo&isLegacy=true&title=esri-leaflet:-an-introduction)
  * [2015 Video - Esri Leaflet: Advanced Topics](http://www.esri.com/videos/watch?videoid=4315&channelid=LegacyVideo&isLegacy=true&title=esri-leaflet:-advanced-topics)
  * [2015 Video - Extend Esri Leaflet with Leaflet Plug-ins](http://www.esri.com/videos/watch?videoid=4420&channelid=LegacyVideo&isLegacy=true&title=extend-esri-leaflet-with-leaflet-plug-ins)
  * [Samples with AngularJS, Browserify, drag&drop, RequireJS, etc](https://github.com/Esri/developer-support/tree/gh-pages/web-leaflet)
  * [15 repos: esri-leaflet, esri-leaflet-geocoder, plugins, ...](https://github.com/search?q=org%3AEsri+leaflet)
  * [A leaflet plugin to display ArcGIS Web Map](https://github.com/ynunokawa/L.esri.WebMap)

* Bootstrap | [@alaframboise](https://github.com/alaframboise)  [@TheBlueDog](https://github.com/TheBlueDog) | Calcite: [@paulcpeterson](https://github.com/paulcpeterson) & [@nicolaswise](https://github.com/nicolaswise)

  * [2015 Video - Bootstrap: Taking Your Mapping UI and UX to the Next Level](http://video.esri.com/watch/4369/bootstrap-taking-your-mapping-ui-and-ux-to-the-next-level) – [PDF](http://proceedings.esri.com/library/userconf/devsummit15/papers/dev_int_154.pdf)
  * [A light-weight JS/CSS extension for to combine Bootstrap with ArcGIS JS (3.x) ](https://github.com/Esri/bootstrap-map-js)
  * [How to use our API for JavaScript (3.x) with Bootstap via Dojo-bootstrap](https://github.com/Esri/dojo-bootstrap-map-js)
  * [Calcite-maps: A modern framework for designing map apps with Bootstrap](https://github.com/Esri/calcite-maps)

* jQuery Mobile | Follow: [@andygup](https://github.com/andygup)
  * [Dynamically resizes map when used in multi-view apps](https://github.com/Esri/jquery-mobile-map-js)

* Knockout | Follow: [@snydercoder](https://github.com/snydercoder)
  * [Video 2015 - Building Map Apps with Knockout and the Esri JavaScript API](http://video.esri.com/watch/4539/building-map-apps-with-knockout-and-the-esri-javascript-api)
  * [DevSummit 2013: Knockout, backbone and Angular samples](http://driskull.github.io/framework-samples-js)

* Backbone | Follow: [@mjuniper](https://github.com/mjuniper)
  * [DevSummit 2013: Knockout, backbone and Angular samples](http://driskull.github.io/framework-samples-js)
  * [Video 2012 - Have a Little Backbone: An MVC JavaScript Framework for ...](http://video.esri.com/watch/1257/have-a-little-backbone-an-mvc-javascript-framework-for-your-next-generation-apps#sthash.FjPVzjoC.dpuf)

* Ember | Follow: [@ffaubry](https://github.com/ffaubry) & [@odoe](https://github.com/odoe) & [@dbouwman](https://github.com/dbouwman)
  * [Ember CLI Addon for using AMD libraries](https://github.com/Esri/ember-cli-amd)

* React | Follow: [@odoe](https://github.com/odoe) & [@tomwayson](https://github.com/tomwayson)
  * [EsriJS with React example](https://github.com/odoe/esrijs-react)
  * [Using ErsiJS 4.0 View Models with React](https://github.com/odoe/esrijs4-vm-react)
  * [ReactJS demo using BaconJS](https://github.com/odoe/reactflux)
  * [Demo app using ReactJS with Esri-Leaflet](https://github.com/odoe/reactmap)
  * [How to lazy load the ArcGIS API for JS in a react-router application](https://github.com/tomwayson/esri-react-router-example)

* Polymer | Follow: [@mjuniper](https://github.com/mjuniper)
  * [DevSummit 2015: A set of Esri web components built using the Polymer library](https://github.com/JamesMilnerUK/esri-polymer)
  * [DevSummit 2014: Mike Juniper Polymer demo](https://github.com/mjuniper/polymer-demo-ds2014)

* PhoneGap | Follow: [@andygup](https://github.com/andygup) & [@lheberlie](https://github.com/lheberlie)
  * [2015 Video: Native Apps using PhoneGap+jQuery+ArcGIS ](http://video.esri.com/watch/4293/arcgis-api-for-javascript-_dash_-building-native-apps-using-phonegap-and-jquery) – [PDF](http://proceedings.esri.com/library/userconf/devsummit15/papers/dev_int_170.pdf)
  * [ArcGIS JavaScript samples for use with PhoneGap/Cordova](https://github.com/Esri/quickstart-map-phonegap)

* Web AppBuilder | Follow: [@rscheitlin](https://github.com/rscheitlin) & [@tomwayson](https://github.com/tomwayson) & [gavinr](https://github.com/gavinr)
  * [Web AppBuilder Developer Resources](https://github.com/Esri/developer-support/tree/gh-pages/web-app-builder)

* CMV | Follow: [@tmcgee](https://github.com/tmcgee) & [@DavidSpriggs](https://github.com/DavidSpriggs)
  * [The Configurable Map Viewer - CMV](http://docs.cmv.io/en/1.3.4/)

----

By the way, we should rename the web-app-builder to web-appbuilder, right? ^_^

Best Regards!

**Comment by jgravois** [comment]
sounds good to me!

**Comment by hhkaos** [comment]
:+1: !
I just [updated a little bit the readme](https://github.com/hhkaos/developer-support/blob/master/web-app-builder/README.md) with more info (PR waiting to be accepted)

**Comment by NoashX** [comment]
is this still an open issue @hhkaos ?

**Comment by jgravois** [comment]
@hhkaos has actually already made a lot of headway on a more definitive *resources* style repo and a calcite website to share web samples

https://github.com/esri-es/awesome-arcgis
https://esri-es.github.io/arcgis-web-samples/

i think we should link to these resources from developer-support and chip in and help him in his open source repos!

**Comment by hhkaos** [comment]
Thx John for the update :) and happy new year by the way!!.

I'm still updating the awesome list of resources (in a [personal repo](https://github.com/hhkaos/awesome-arcgis)), I did a fork from that in the Esri Spain account to add some [localised resources](https://github.com/esri-es/awesome-arcgis/tree/master/front-end/dojo/web-appbuilder#recursos-en-español).

It is a lot of work for just one person so I may take me a few months before I have something "decent". I guess we should link the awesome list repo after we host it on the Esri Account, don't you think? (if you think that could be possible).

Cheers!

**Comment by jgravois** [comment]
closing, as there are no action items here, but i *highly* encourage folks to get involved and give @hhkaos a hand updating his cool projects!
