### ISSUE TITLE
Problems running code in 10.5

### ISSUE THREAD

**Issue by emilylecroixwright** [Esri/developer-support#300]
Run the script in 10.5 and only get complete message. Does not change path names in project. 
Also tested script in 10.3 the script worked but corrupted some of the 10.5 .mxd. Can anyone help?

**Comment by nohe427** [comment]
Can you be a little more explicit on which script you ran?

**Comment by emilylecroixwright** [comment]
https://github.com/Esri/developer-support/blob/master/python/arcpy-python/find-and-replace-data-sources-in-mxd/find_and_replace_data_sources.py

**Comment by nohe427** [comment]
When you say corrupted, do you mean that it changed the MXDs to a point which they cannot be opened (10.5 MXDs only) or do you mean that it switched the working data sources to bad data sources?  Are you trying to open the 10.5 MXDs in 10.3?

**Comment by emilylecroixwright** [comment]
Yes got an error message opening the .mxd. Would no longer open. Ran the script on 30 different .mxd in different sub folders. The .mxd that corrupted had group layers. The script successfully remapped other .mxd with group layers.  The error message did say the project was created in a newer version of ArcGIS.

**Comment by nohe427** [comment]
MXDs are not backwards compatible.  You should be able to open that MXD on a 10.5 machine.  Are you able to open that MXD on a 10.5 machine?

**Comment by emilylecroixwright** [comment]
Yes copy the original back and open fine in 10.5. The .mxd was original created in 10.5.

**Comment by emilylecroixwright** [comment]
We have changed server. I'm having to change the path name for 10k .mxd.

**Comment by emilylecroixwright** [comment]
The script that worked I was using 10.3 to change the pathnames in 10.5 project. I upgraded my test machine to 10.5 yesterday to see if I got the same error. This is when I found out the script did not work in 10.5.

**Comment by nohe427** [comment]
So, I don't believe the script corrupted the MXD since the MXDs created in 10.5 cannot be opened in 10.3, they can only be opened in 10.5 or newer.  I think the bigger issue here is that you are having trouble reading the MXDs and updating the paths using Python at ArcMap 10.5.  If I get a chance later today, I will try to open an MXD via Python and see if I can get the same issues that you are running into.  I may not have time to explore this today or right now for that matter, as I am busy working on other tasks at the moment.

**Comment by emilylecroixwright** [comment]
Ok, thank you for your help. The main issue is that the script will not run in 10.5. Just says complete.

**Comment by nohe427** [comment]
@emilylecroixwright - I just spoke with a colleague who was test ran the script for me and it sounds like it might be a configuration setting on your end?  For the path2Mxds argument, are you supplying a UNC path, a mapped path, or a path that is local?

Thanks,
Alexander

**Comment by emilylecroixwright** [comment]
UNC path

**Comment by nohe427** [comment]
Can you confirm that the UNC path is correct by placing it in the file explorer window and confirming that it opens up a new window to that location?

**Comment by emilylecroixwright** [comment]
All path are correct

**Comment by emilylecroixwright** [comment]
[cid:image001.png@01D2C3FF.355D27E0]

**Comment by nohe427** [comment]
Sorry, but that image did not come through

**Comment by nohe427** [comment]
```python
import arcpy
import os

def find_and_replace(MXD_workspace, oldPath, newPath):
    arcpy.env.workspace = MXD_workspace
    path = arcpy.env.workspace
    
    print "MXD_WORKSPACE " + MXD_workspace
    print "PATH " + path

    for root, dirs, files in os.walk(path):
        for name in files:
            if name.endswith(".mxd"):
                mxd_name = name
                fullpath = os.path.join(root,name)
                print mxd_name
                print fullpath
                mxd = arcpy.mapping.MapDocument(fullpath)
                for df in arcpy.mapping.ListDataFrames(mxd):
                    for flayer in arcpy.mapping.ListLayers(mxd, "*", df):
                        if flayer.isFeatureLayer or flayer.isRasterLayer:
                            try:
                                mxd.findAndReplaceWorkspacePaths(oldPath, newPath, False)
                                print "Repaired the path for " + name
                            except:
                                print(mxd_name + " cannot replace paths")
                mxd.save()
                del mxd
    print "complete..."

if __name__ == '__main__':
    find_and_replace(r"path2MXDs", r"path2oldGDB", r"path2newGDB")
```

Can you try running this script and letting me know what is printed besides complete?

This should print out the MXD_workspace argument as well as the Path argument that is later set in the script

**Comment by nohe427** [comment]
We can also take this to a more private conversation by emailing me directly at anohe@esri.com

**Comment by nohe427** [comment]
We resolved offline.

**Comment by emilylecroixwright** [comment]
closeed

**Comment by emilylecroixwright** [comment]
closed
