### ISSUE TITLE
wfsLayer arcgis API for JavaScript 3.23

### ISSUE THREAD

**Issue by ly2013203742** [Esri/developer-support#329]
I want adding filters for wfsLayer， just want to load one of the layers.So how to make "request=getfeature". Now I set featureid on customParameters,but I view the reques is 'GetCapabilities'. You can see the code from here:https://github.com/ly2013203742/Test-The-Install/blob/master/wfsLayer.html
![image](https://user-images.githubusercontent.com/14887020/34337706-a32674ac-e99c-11e7-8ff0-d2a373d5de7d.png)

**Comment by jgravois** [comment]
hi @ly2013203742! this isn't the best place to ask for help using the ArcGIS API for JavaScript unless you have a specific question about a code sample that is published in _this_ repository. you'll attract a lot more eyes on [GeoNet](https://community.esri.com/comunity/developers/web-developers/arcgis-api-for-javascript).

**Comment by ly2013203742** [comment]
Thank you for your advice. I'll do it.
