### ISSUE TITLE
Not working with 'ARCGIS_SERVER'

### ISSUE THREAD

**Issue by vikshut** [Esri/developer-support#337]
Hi,

I am trying to publish as a feature service into my ArcGIS portal. For this I need to create the sddraft with ARCGIS_SERVER' as the server type. After this when I run the code to modify from MapService to FeatureService (within Arcmap's python window), the runs successfully without any errors but doesn't make any changes to the sddraft.

Would appreciate a fix for this. Thanks.

**Comment by jgravois** [comment]
you're going to have to clarify which code sample you are trying to adapt because there are literally dozens in this project.
