### ISSUE TITLE
error:14077410 sslv3 alert handshake failure

### ISSUE THREAD

**Issue by insomniak90** [Esri/developer-support#338]
I am using this script and am able to run the update method ok. unfortunately I'm getting the error below when calling the deleteTiles and updateTiles methods. I'm assuming this has to do with the new TLS1.2 security requirement. But have no clue where to start. Greatly appreciate any help. 
>>>
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
<<<

**Comment by insomniak90** [comment]
please excuse my newbie-ness to github... this is in reference to developer-support / python / general-python / update-tile-service-from-tpk / updateTilesFromTPK.py

**Comment by jgravois** [comment]
any ideas @kgerrow?

**Comment by insomniak90** [comment]
ok to close issue. I ended up installing python 2.7.16 and the script ran successfully.

**Comment by jf990** [comment]
without digging deeper this issue sounds like it is related to the TLS 1.2 upgrade that we recently did and older versions of SSL handshake will be rejected. upgrading a client to TLS 1.2 compatible SSL library might address it.
