### ISSUE TITLE
document guidelines for contributing

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#4]
i suggest we enforce a fork and pull model for this repository (or at a bare minimum require submitting Pull Requests to merge into master from dedicated feature branches) and explicitly prohibit that contributors push directly to the master branch.

https://help.github.com/articles/using-pull-requests/

this will be beneficial for several reasons

1. a second set of eyes helps spot errors and gives an opportunity to improve both code and documentation quality.
2. it helps avoid merge conflicts
3. its good practice for contributing to strangers projects and working on a codebase which requires more extensive collaboration.

its also important that we document guidelines that explain what is required in order to get contributions merged.  particularly the inclusion of enough contextual information in a readme specific to an individual sample to explain to anyone perusing the repository what it should be able to help them accomplish.

**Comment by nohe427** [comment]
Am I tackling the:

"its also important that we document guidelines that explain what is required in order to get contributions merged." :question:

**Comment by jgravois** [comment]
yup.  we need a document that states:
1. that PRs are required, even from those that have push access to the repo
2. links to documentation that explains more about forking and/or feature branches to keep the master branch clean
3. an explanation of what makes an ideal PR (organized code w/ no unnecessary dependencies which includes substantial enough explanation to make it useful)

**Comment by alaframboise** [comment]
I agree. This repo is awesome, but having xx number of members with write/push access will result in chaos. I also didn't see a reference to https://github.com/Esri/contributing in the README.md.

**Comment by nohe427** [comment]
Added this to the wiki:

https://github.com/Esri/developer-support/wiki/Resources-To-Learn-Git

**Comment by jgravois** [comment]
:+1: linked to this new wiki in #16

closing.
