### ISSUE TITLE
add links in contributor help to 'github guides'

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#48]
i just found this [great site](https://guides.github.com/) which breaks out a variety of essential github/git topics into bite sized articles and videos.  its a great resource so i think it'd be a good idea to include links from our own help.

anyone up for tackling this 'enhancement'?

**Comment by jgravois** [comment]
this too: https://twitter.com/cthydng/status/575483540202106880?s=09

supremely concise.

**Comment by NoashX** [comment]
I'm interested @jgravois, having just gone through a tutorial of using SourceTree with the help of @afili. Did you envision an entire new page about GitHub worklows, or just a couple of sentences and links on the README or CONTRIBUTING pages?

**Comment by goldenlimit** [comment]
@jgravois @NoashX I do think currently we need more practices on Github using. I do feel I got a little better but still daily usage is really a good lesson as well! :thu
