### ISSUE TITLE
remove 'Support Services' as a group with push access to this repo

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#56]
everyone knows im **all for** open source and 'defaulting to open', but i think we went a bit overboard giving the entire [Support Services](https://github.com/orgs/ArcGIS/teams/support-services) team `push` access to this repo and consequently automatically subscribing them to email notifications regarding its activity.

#### why?
1. i've received a couple emails from users who felt the notifications were spam.
2. i think some folks get more intimidated about contibuting knowing that their comments, etc. will be email blasted to a big group.
3. lets face it.  github is cooler when its nitch.

obviously there are pros and cons to both approaches, but my general opinion is: 
* make repos public (or at least public to the entire arcgis org)
* only grant push privileges to those that have explicitly declared interest in contributing/maintaining

to do:
- [ ] create a new smaller [write access team](https://help.github.com/articles/permission-levels-for-an-organization-repository/) composed of the folks who've already jumped in and helped, or expressed interest

its not hard for others to fork and pull if they want to particate and add more folks to the team in the future.

i'd like to give this issue a week or so to collect other comments to see if anyone else feels differently.

(this is more or less a duplicate ArcGIS/esri-support-sql-repository/issues/3)

**Comment by nohe427** [comment]
I'd like the idea.  I have been pushing a lot of new updates lately and think it would be beneficial if I didn't email 60+ ppl everytime I submit a PR.

**Comment by afili** [comment]
I like the idea too. So basically what we are saying is that we will have a smaller group of people with write access, so only these people will be receiving emails and will be able to push directly to the repository. Also, this does not limit a person with read-only access to contribute since he/she can still fork and submit a pull request. Then somebody else with push permissions can merge. Is this correct?
Before we proceed with any changes, I want to discuss this with Nidhi just in case she has any other thoughts.

**Comment by jgravois** [comment]
> this does not limit a person with read-only access to contribute since he/she can still fork and submit a pull request.

exactly. :smile:

**Comment by NoashX** [comment]
I'm on board for this new system as well. Then maybe a couple weeks/months down the road we can have another GitHub Brown Bag sessions and recruit some new folks for the smaller admin team.

**Comment by afili** [comment]
Sounds good. Brought this up during group meetings and most analysts like the idea. Management is also on the same page.

**Comment by phpmaps** [comment]
@afili @jgravois  ok i am on board.

**Comment by jgravois** [comment]
ok.  i just went ahead and trimmed down the 'Developer Support' team to 29 members and notified those removed that we are happy to add them back if they're interested in getting involved.

**Comment by jgravois** [comment]
fyi, removing someone from a group doesn't automatically unsubscribe them from repositories so we still have almost 70 watchers.  this seems fine to me.

**Comment by afili** [comment]
awesome! thank you @jgravois
