### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by smnorris** [Esri/developer-support#59]
In extract-json-from-arcmap-layer, the mxd to msd link is broken.

http://ess.maps.arcgis.com/home/item.html?id=2467871513044597a6a64c9d9d025627

```
The item you requested cannot be found. 
The item may have been deleted or you may have entered an incorrect URL.
```

**Comment by phpmaps** [comment]
Thanks for pointing this out.. let me see if I can work the proper link.  Stay tuned.

**Comment by phpmaps** [comment]
Ok, so I know what happened.  That account (which was mine) was just recently deleted - not sure what the process is for getting back that content.  I assume I have it somewhere on disk ... I am first checking with an Admin.

**Comment by jgravois** [comment]
if we can't find the missing toolbox [here](https://github.com/Esri/developer-support/tree/master/arcobjects-net/extract-json-from-arcmap-layer) its probably best for someone (anyone) to just remove the sample.

**Comment by smnorris** [comment]
Now that I look more closely (6 months later!) I see that it is just an arcpy.mapping tool, so it should be available to any user with arcgis desktop installed.

**Comment by jgravois** [comment]
@smnorris thanks for taking the time to write back.  does this mean its safe to close this issue now?

**Comment by smnorris** [comment]
Sure but you might want to remove the existing link and point to the tool's
documentation instead.
