### ISSUE TITLE
make sure javascript samples link to 'gh-pages' branch in readme as demo

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#61]
for example, in 2945f5ae663375828b5ad35b6c99e10e7537259d we'd be better off linking to the app [here](http://esri.github.io/developer-support/web-js/dynamic-layer-popups/) than [here](https://dl.dropboxusercontent.com/u/79881075/dynamic-layer-popups.html)

my presentation slides can be found here:
http://jgravois.github.io/presentations/git-er-done-2/

**Comment by jgravois** [comment]
this will require that we keep the `gh-pages` branch in sync with `master`

**Comment by jgravois** [comment]
happy to leave this closed, but it'd be helpful for folks to go back through more existing samples and add live links to the readmes...

**Comment by nohe427** [comment]
@jgravois I think most of the web-js readmes were updated to reflect the gh-pages links.  There is only one that is not reflecting the gh-pages link and that may be because the gh-pages branch is no longer in sync with master

**Comment by jgravois** [comment]
oh sweet.  i see it in the commit history now.  let me know if y'all need any help merging the latest changes on `master` into `gh-pages` locally and then pushing upstream.  as long as people keep their work **off** the `gh-pages` branch itself, it'll always be a simple [fast-forward](http://ariya.ofilabs.com/2013/09/fast-forward-git-merge.html).

**Comment by nohe427** [comment]
@jgravois I was trying to fast forward it earlier today and was having trouble doing so.  Would you be able to do it on your end?

**Comment by jgravois** [comment]
done.

```
git checkout gh-pages
git fetch upstream
git merge upstream/master
git push origin gh-pages
```

**Comment by nohe427** [comment]
Pull request #68 should be the last sample.
