### ISSUE TITLE
minor error in 'SUBMITPR.md'

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#63]
> Clone a copy of the repository locally by clicking the "Clone in desktop" or "Download ZIP" button

~~or "Download ZIP" button~~ 

when selecting 'Download ZIP' only the current state of the files in the repository are packaged, commit history and information about other branches is stripped out (more info [here](http://www.quora.com/Git-What-is-the-differences-between-forking-cloning-and-downloading-the-project-as-a-zip)). 

anyone **new** game for making this small change and submitting a pull request?

**Comment by nohe427** [comment]
@jgravois By referencing this issue in PR 64, did this automatically close the issue?

**Comment by jgravois** [comment]
[yup](https://help.github.com/articles/closing-issues-via-commit-messages/).  extreme bonus points to @danmaps :smile:
