### ISSUE TITLE
suggestions for improvements to the 'Join Data Source' sample

### ISSUE THREAD

**Issue by jgravois** [Esri/developer-support#79]
a customer at UC just showed me a really cool sample in here where we show how to create a join on the fly and create a new renderer using DynamicLayers [here](https://github.com/Esri/developer-support/tree/master/web-js/join-data-source) but she was having a hard time understanding what was going on.

in helping her digest the sample, i have the following suggestions for improvements:
- [x] JS and CSS need to be formatted/tabbed consistently
- [x] the hardcoded reference to @AkshayHarshe 's proxy needs to be removed
- [x] the sample needs inline code comments to describe whats going on.  particularly that its up to the developer to **know** a *workspaceID* because its not something that is exposed by ArcGIS Server

the readme needs:
  - [x] formatted (so that the numbered bullets each have their own line)
  - [x] links need to be included to the relevant ArcGIS Server documentation for setting up DynamicLayers and workspaces.
  - [x] we need to link to the live gh-pages sample from the readme

is anyone up for tackling this?  it needn't be the job of the original author.

**Comment by goldenlimit** [comment]
Hi John let me take a shoot
