### ISSUE TITLE
AppStudio Folder

### ISSUE THREAD

**Issue by marlak** [Esri/developer-support#99]
Hey guys!

I was just chatting with @esoekianto and @bsnider about possibly creating a folder for [appStudio](http://appstudioprd.arcgis.com/) (qml) samples. It just went into beta 3 and started coming in all the support channels so we thought it might be a good idea. Any thoughts? :thought_balloon:

**Comment by NoashX** [comment]
:information_desk_person: totally! sounds like a good idea, I'm sure it'll grow real soon

**Comment by nohe427** [comment]
I'd say once we have something to put in there let's create it.

**Comment by goldenlimit** [comment]
@nohe427 Work from :house:? That's too much :neutral_face:

**Comment by nohe427** [comment]
@goldenlimit Nah, I am on campus this week.

**Comment by bsnider** [comment]
@nohe427 I recommend we maintain two separate folders.  The AppStudio framework is built with a folder structure that wraps the Qt Runtime for ArcGIS.  The import paths to the same modules therefor vary when using AppStudio vs the 'pure' Qt Runtime for ArcGIS.

**Comment by nohe427** [comment]
Since we do have some appstudio samples that can be used sitting in the qt folder, I will move them over to an appstudio folder and then close this issue
